### ISSUE TITLE
Add Confirmation Dialog for Closing Chat Room

### ISSUE THREAD

**Issue by StaticAccess** [StaticAccess/Lynai#1]
### Description
Currently, when a user clicks the close button (X) in the chat room, the room is immediately closed without any confirmation. This can lead to accidental room closures and a poor user experience. We need to implement a confirmation dialog to prevent unintended actions.
### Current Behavior
The close button immediately triggers the room closure:
`          <Button variant="ghost" onClick={handleCloseRoom} className="text-destructive">
            <X size={24} />
          </Button>
`
- FrontEnd/app/chat-room/[roomId]/page.tsx
### Desired Behavior
When a user clicks the close button, a confirmation dialog should appear asking, "Are you sure you want to close this room?" with "Yes" and "No" options.
### Implementation Guidelines
1. Add a new state variable to control the visibility of the confirmation dialog.
2. Create a new Dialog component for the confirmation.
3. Modify the handleCloseRoom function to show the confirmation dialog before proceeding with room closure.
4. If the user confirms, proceed with the existing room closure logic.
5. If the user cancels, keep the room open.

### Testing

- Verify that clicking the close button shows the confirmation dialog.
- Confirm that selecting "Cancel" keeps the room open.
- Confirm that selecting "Close Room" closes the room and redirects to the home page.

### Additional Notes
- Ensure the confirmation dialog is responsive and accessible.
- Consider adding a keyboard shortcut (e.g., Esc key) to close the confirmation dialog.
### Testing Checklist
[ ] Clicking the close button (X) opens the confirmation dialog
[ ] Clicking "Cancel" closes the dialog without closing the room
[ ] Clicking "Close Room" closes both the dialog and the room
[ ] Pressing ESC key closes the dialog without closing the room
[ ] Clicking outside the dialog closes it without closing the room
[ ] Toast notifications appear appropriately for success/error cases

### Related Files
- FrontEnd/app/chat-room/[roomId]/page.tsx
- FrontEnd/components/ui/dialog.tsx
- FrontEnd/hooks/use-toast.ts
![Screenshot 2024-10-27 020951](https://github.com/user-attachments/assets/b181f5cc-eae2-47ac-80ba-7b1c929b5045)

**Comment by slusy** [comment]
Hey, I would like to work on this.

**Comment by StaticAccess** [comment]
you can create PR after done.

**Comment by slusy** [comment]
<img width="1001" alt="image" src="https://github.com/user-attachments/assets/4c24d99b-1ef2-46f5-9fe1-4bb4108d506c">

<img width="1001" alt="image" src="https://github.com/user-attachments/assets/fa1e841a-5d8d-4204-8361-5da67de971d4">

There are few errors in the toast component due to typescript. Should I make `open` and `onOpenChange` as optional or leave it as it is?

**Comment by StaticAccess** [comment]
Leave it as it is. Our frontend is not built yet, which is why we haven't fixed that issue. Just check 'npm run dev' working or not.

**Comment by StaticAccess** [comment]
Production is not built yet, so you can create new issues to improve the codebase.
